#!/bin/bash
shopt -s nullglob

for file in **/*.gif
do
	    if [[ -f "$file" ]]
		        then
				        name=${file##*/}
					        name=${name%.*}
						        echo "$name"
							    fi
						    done | LC_COLLATE=C sort -f | uniq

						    echo
